version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: kp-service-db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    image: kp-docker/kp-generation-service:latest
    container_name: kp-creator-service
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kp-service-db
      SPRING_DATASOURCE_USERNAME: user-name
      SPRING_DATASOURCE_PASSWORD: strong-password
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  ui:
    image: nginx:alpine
    container_name: react-ui
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../ui/build:/usr/share/nginx/html
      - ../ui/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  local_pgdata:
  pgadmin-data: