version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: NyPaSBpyfKTnnM8qSAUr0sOdpeG50NwI
      POSTGRES_DB: kp-service-db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: nXmzu5YONSnB4oIBw0riDvonMChHB4n4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    image: kp-docker/kp-generation-service:latest
    container_name: kp-creator-service
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kp-service-db
      SPRING_DATASOURCE_USERNAME: postgresUser
      SPRING_DATASOURCE_PASSWORD: NyPaSBpyfKTnnM8qSAUr0sOdpeG50NwI

volumes:
  local_pgdata:
  pgadmin-data: